include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    always_use_package_imports: ignore
    prefer_relative_imports: error

  exclude:
    - "bin/cache/**"
    # Ignore protoc generated files
    - "dev/conductor/lib/proto/*"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
