name: repo_viewer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  webview_flutter: ^3.0.0
  flash: ^2.0.1
  auto_route: ^3.2.0
  material_design_icons_flutter: ^5.0.6595
  json_annotation: ^4.4.0
  sembast: ^3.1.0+2
  path: ^1.8.0
  path_provider: ^2.0.3
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^1.1.0
  lint: ^1.7.2
  auto_route_generator: ^3.2.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
